framework:
    secret: test

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     :memory:
        memory:   true
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
